version: '3.8'
services:
  database:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
  keycloak:
    image: mihaibob/keycloak:15.0.1
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=h2
      - JAVA_OPTS=-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/keycloak-dump.json
    volumes:
      - type: bind
        source: ./tmp/keycloak-dump.json
        target: /tmp/keycloak-dump.json
        read_only: true
    ports:
    - "8888:8080"
  sqs:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"
      - "9325:9325"
